#!/bin/bash

version_code=23.2
version_date=99999999

build_date="$(LANG='en_US' date +"%Y%m%d")"

VERSION="${version_code}.${build_date}"
version_p="${version_code}.${version_date} [build ${build_date}]"
CWD="$(readlink -fn "${BASH_SOURCE[0]}")"
CWD="$(dirname "${CWD}")"

case "$(uname -s)" in
	*Darwin* | *BSD* )
		export sumsha256="shasum -a 256"
		export statx="stat -f %Z"
	;;
	*Linux* )
		export sumsha256="sha256sum"
		export statx="stat -c %Z"
	;;
esac

# DIRS
datafolder="${CWD}/data"
repofolder="${datafolder}/repo"

# AppsFolder
appsfolder[0]="Full"
appsfolder[1]="${appsfolder[0]}/system"
appsfolder[2]="${CWD}/${appsfolder[1]}"
appsfolder[3]="${appsfolder[1]}/app"
appsfolder[4]="${appsfolder[1]}/priv-app"
appsfolder[9]="OsmAnd/system"
appsfolder[10]="${CWD}/${appsfolder[9]}"
appsfolder[11]="BromiteWebView/system"
appsfolder[12]="${CWD}/${appsfolder[11]}"
appsfolder[13]="MulchWebView/system"
appsfolder[14]="${CWD}/${appsfolder[13]}"

# ripped-out
appsfolder[5]="Google/gsync"
appsfolder[6]="${CWD}/${appsfolder[5]}"
appsfolder[7]="Google/swipe"
appsfolder[8]="${CWD}/${appsfolder[7]}"


for funcfile in pkg update common download database report; do
	source "${datafolder}/build-package.${funcfile}" || exit 1
done

[[ -z "${1}" ]] && show_help

for opt in "${@}"; do
	case "${opt}" in
		full)
			check_nanodroid || error "run 'build-package pull' first!"
			mk_pkg_full
		;;

		uninstaller )
			mk_pkg_uninstaller
		;;

		#bromitewebview )
		#	check_nanodroid || error "run 'build-package pull' first!"
		#	mk_pkg_bromite_webview
		#;;

		mulchwebview )
			check_nanodroid || error "run 'build-package pull' first!"
			mk_pkg_mulch_webview
		;;

		systest )
			mk_pkg_systest
		;;

		all )
			check_nanodroid || error "run 'build-package pull' first!"
			mk_pkg_full
			#mk_pkg_uninstaller
			#mk_pkg_bromite_webview
			mk_pkg_mulch_webview
			#mk_pkg_systest
			#create_report
		;;

		ver )
			increase_version_number "${2}" "${3}"
			exit "${?}"
		;;

		bump )
			increase_module_version
			exit "${?}"
		;;

		dalvik )
			dalvikize_jar "${2}" "${3}"
			exit "${?}"
		;;

		pull )
			update_indices
			nanodroid_pull
			update_master
			check_nanodroid
		;;

		u-apps )
			update_indices
			update_apps
			update_master
			check_nanodroid
		;;

		#u-bromite )
		#	update_indices
		#	update_webview
		#	update_master
		#	check_nanodroid
		#;;

		check )
			check_nanodroid
		;;

		clean )
			echo -ne "\nAre you sure to delete all untracked files?\n >> enter [y] or [j] to continue: "
			read -r user_input

			case "${user_input}" in
				y | Y | j | J )
					git clean -fdX
				;;

				* )
					echo "aborted"
				;;
			esac
		;;

		report )
			check_nanodroid || error "run 'build-package pull' first!"
			create_report
		;;

		* )
			show_help
		;;
	esac
done
